name: Run Android Emulator Tests

on:
  push:
    branches: [ "main", "mvn" ]
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [29]
        target: [default]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'

      - run: |
          npm install -g appium@2.4.1
          appium -v
          appium driver install uiautomator2@2.42.2
          appium --port 4723 &

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Kill existing emulators (if any)
        run: |
          adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done || true

      - name: Restart ADB Server
        run: |
          adb kill-server || true
          adb start-server

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: ${{ matrix.target }}
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 1800
          emulator-port: 5554
          disable-linux-hw-accel: true

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          echo "Aguardando o emulador inicializar completamente..."
          while [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]]; do
            sleep 5
          done
          echo "Emulador pronto!"

      - name: Grant Permissions for Tests
        run: |
          adb shell pm grant com.seuapp.android android.permission.ACCESS_FINE_LOCATION || true
          adb shell pm grant com.seuapp.android android.permission.ACCESS_COARSE_LOCATION || true

      - name: Run Instrumentation Tests
        run: ./gradlew connectedCheck

      - name: Collect Test Results
        if: always()
        run: |
          mkdir -p test-results
          cp -r app/build/reports/androidTests test-results/ || true
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-test-results
          path: test-results

      - name: Stop Emulator
        run: adb -s emulator-5554 emu kill || true
