name: Run Appium Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Appium 2.16.1
        run: |
          npm install -g appium@2.16.1
          appium -v

      - name: Install UiAutomator2 Driver
        run: |
          appium driver install uiautomator2
          appium driver list --installed

      - name: Start Appium Server
        run: |
          appium --log-level debug &
          echo $! > appium_pid.txt 

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 5
          script: |
            echo "Emulador pronto!"
            mvn clean test surefire-report:report  

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/reports

      - name: Stop Appium Server
        run: |
          kill $(cat appium_pid.txt) || true
          echo "Appium Server stopped."